### PR TITLE
Add English Translation and update packages

### PR DESCRIPTION
**Pull request by harryadel**

### CODE REVIEW

**Review by fliptation — COMMENTED** [review]
the locale switcher does not work on /referenzen (success stories)

**Comment by fliptation** [comment]
blog has 404

**Comment by harryadel** [comment]
Thanks for the heads up. Will notify you once everything is fixed and ready to go. :+1:

**Comment by fliptation** [comment]
http://localhost:3010/en/ueber-uns the URL should change, ie. (en/about)

**Comment by fliptation** [comment]
> http://localhost:3010/en/ueber-uns the URL should change, ie. (en/about)

We should use Internationalized Routing https://nextjs.org/blog/next-10#internationalized-routing

**Comment by harryadel** [comment]
@fliptation please pull and recheck internationalized routes should be working now. You can alternate names of English routes located in `translations/getPathname.js`.

**Pull request merged**
